language: php

php:
    - 5.4
    - 5.5

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

before_script:
    - composer install
    - bash bin/tests/installWpTests.sh wordpress_test root '' localhost $WP_VERSION

script: ./bin/tests/phpunit.phar -c ./bin/tests/
